### ISSUE TITLE
node.rugpullindex.com seems to fail because of too many requests by neume 

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#113]
```
Error: FetchError: request to https://node.rugpullindex.com/ failed, reason: getaddrinfo ENOTFOUND node.rugpullindex.com
    at Worker.<anonymous> (file:///Users/timdaub/Projects/neume-network/core/src/strategies/src/lifecycle.mjs:149:13)
```

- investigate if it works with other nodes
- now, multiple strategies may request the node simultaneously, it may be better to limit the concurrency some more
- see https://github.com/neume-network/extraction-worker/issues/15
- What if we turn up concurrency all the way and e.g. request using alchemy or infura?

**Comment by il3ven** [comment]
I read this https://github.com/nodejs/node/issues/5436#issuecomment-378960999. It says that under high load the dns lookup fails and we get ENOTFOUND. A solution proposed there is to cache dns request in your application so that a call to the OS is not made.

Since the above issue does not always occur I can't reliably test if dns cache solves the problem or not.

**Comment by TimDaub** [comment]
do I understand correctly that this is a client side error that hasn't to do with the node?

**Comment by il3ven** [comment]
It's a possibility that this is a client side error. I saw various comments where people have reported the same error (i.e. ENOTFOUND) under high load.

**Comment by TimDaub** [comment]
then let's close it until it comes up again
